export const colors = {
  background: '#f7faf5',
  surface: '#f7faf5',
  surfaceDim: '#d8dbd6',
  surfaceBright: '#f7faf5',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f1f4f0',
  surfaceContainer: '#ecefea',
  surfaceContainerHigh: '#e6e9e4',
  surfaceContainerHighest: '#e0e3df',
  onSurface: '#191c1a',
  onSurfaceVariant: '#434844',
  inverseSurface: '#2d312e',
  inverseOnSurface: '#eff2ed',
  outline: '#737873',
  outlineVariant: '#c3c8c2',
  primary: '#4d6054',
  onPrimary: '#ffffff',
  primaryContainer: '#66796c',
  onPrimaryContainer: '#f6fff6',
  inversePrimary: '#b7ccbc',
  secondary: '#58605b',
  onSecondary: '#ffffff',
  secondaryContainer: '#dae2db',
  onSecondaryContainer: '#5c645f',
  tertiary: '#595d5b',
  onTertiary: '#ffffff',
  tertiaryContainer: '#727574',
  onTertiaryContainer: '#fbfdfb',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#d2e8d8',
  primaryFixedDim: '#b7ccbc',
  onPrimaryFixed: '#0d1f15',
  onPrimaryFixedVariant: '#384b3f',
  secondaryFixed: '#dce4de',
  secondaryFixedDim: '#c0c8c2',
  onSecondaryFixed: '#161d19',
  onSecondaryFixedVariant: '#414944',
  surfaceVariant: '#e0e3df',
  cardBorder: '#e8f0e9',
  cardShadow: 'rgba(124, 144, 130, 0.12)',
  scrim: 'rgba(0, 0, 0, 0.55)',
};

export type ColorKey = keyof typeof colors;
